FROM debian:latest
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    build-essential \
    python \
    python3-dev \
    python-pip \
    python3-pip \
    python3-setuptools \ 
    htop \
	ruby \
	php \
#	default-jdk \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*